Port PPC_TASKS CI scoping and MPI timing fixes (#1514)
* Add PPC_TASKS build selector (#775)

Add `PPC_TASKS` for developers to make local builds much more
lightweight by building only selected tasks

(cherry picked from commit ff1f4300f7f23f33d66fbf3ce55a0764288c4f8f)

* Stabilize MPI test timing (#780)

Synchronize ranks before timed sections so scheduler skew and barrier
waits are not counted as task runtime, preventing rare timeout flakes
like these:

```
[ RUN      ] PicMatrixTests/NesterovARunFuncTestsProcesses3.MatmulFromPic/nesterov_a_test_task_processes_3_mpi_enabled_3_3
unknown file: error: C++ exception with description "
Task execute time need to be: time < 1 secs.
Original time in secs: 1.21769
" thrown in the test body.

[       OK ] PicMatrixTests/NesterovARunFuncTestsProcesses3.MatmulFromPic/nesterov_a_test_task_processes_3_mpi_enabled_3_3 (1224 ms)
[  FAILED  ] PicMatrixTests/NesterovARunFuncTestsProcesses3.MatmulFromPic/nesterov_a_test_task_processes_3_mpi_enabled_3_3, where GetParam() = (64-byte object <20-AA 75-60 F6-7F 00-00 C0-6C 6E-60 F6-7F 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 88-77 B8-48 FD-01 00-00>, "nesterov_a_test_task_processes_3_mpi_enabled", (3, "3")) (1225 ms)
[ RUN      ] PicMatrixTests/NesterovARunFuncTestsProcesses3.MatmulFromPic/nesterov_a_test_task_processes_3_mpi_enabled_7_7

job aborted:
[ranks] message

[0] terminated

[1] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 1

[2] terminated

---- error analysis -----

[1] on runnervmqq1k9
D:\a\parallel_programming_course\parallel_programming_course\install\bin\ppc_func_tests aborted the job. abort code 1

---- error analysis -----
 [  PROCESS 1  ]  [  PROCESS 1  ] Traceback (most recent call last):
  File "D:\a\parallel_programming_course\parallel_programming_course\scripts\run_tests.py", line 308, in <module>
    _execute(args_dict, env_copy)
  File "D:\a\parallel_programming_course\parallel_programming_course\scripts\run_tests.py", line 283, in _execute
    runner.run_processes(args_dict["additional_mpi_args"])
  File "D:\a\parallel_programming_course\parallel_programming_course\scripts\run_tests.py", line 247, in run_processes
    self.__run_exec(
  File "D:\a\parallel_programming_course\parallel_programming_course\scripts\run_tests.py", line 122, in __run_exec
    raise Exception(f"Subprocess return {result.returncode}.")
Exception: Subprocess return 1.
Error: Process completed with exit code 1.
```

Please go to the `Preview` tab and select the appropriate template:

* [Submit Student task
(English)](?expand=1&template=task_submission_en.md)
* [Submit Student task
(Russian)](?expand=1&template=task_submission_ru.md)
* [Submit Fix for Student task
(English)](?expand=1&template=task_fix_submission_en.md)
* [Submit Fix for Student task
(Russian)](?expand=1&template=task_fix_submission_ru.md)

(cherry picked from commit a3fb7bb352bf39e08abd6b65f0b1b70b6af6454c)

* [CI] Scope PR builds to changed tasks only if applicable (#781)

Run build for one student task only in 'pull_request' scope. All tests
are being run on push event

(cherry picked from commit 5e0844e56054785b420d682d8856c82af02c43e4)

---------

Co-authored-by: Arseniy Obolenskiy <gooddoog@student.su>